### PR TITLE
Update the dependencies for the CLEASE feedstock, to match the source…

### PR DESCRIPTION
**Pull request by atygesen**
Hi - I'm one of the developers of the CLEASE package.

This MR updates the dependencies for the CLEASE feedstock to match the source run-time dependencies.

Pytest is not necesasry to run CLEASE. Add `click` to make the CLEASE CLI work.
Test the CLI can run.

Updates the doc and home URL to the [readthedocs](https://clease.readthedocs.io/) page.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@atygesen Do you want to add yourself as a maintainer?

**Comment by atygesen** [comment]
That might be good - I can add myself to the recipe. But I havn't worked with these feedstock's before, so I just want to ensure I'm not breaking things.

**Comment by jan-janssen** [comment]
@atygesen Sure, I can always take a look and I am sure you pick it up quite quickly.

**Comment by jan-janssen** [comment]
But you can also add yourself in a separate pull request - I am going to merge this one now. Thanks again.

**Pull request merged**
